<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   
   <xacro:include filename="inertial_macros.xacro"/>
   <xacro:property name="pi" value="3.14159265359"/>
   
    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>




   <material name="white">
    <color rgba="1 1 1 1" />
   </material>

   <material name="orange">
    <color rgba="1 0.3 0.1 1" />
   </material>

   <material name="blue">
    <color rgba="0.2 0.2 1 1" />
   </material>

   <material name="black">
    <color rgba="0 0 0 1" />
   </material>
  
   <!--base link-->

   <link name="base_link">

   </link>
   
   <!--chassis link-->
   <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis"/>
      <origin xyz="-0.1 0 0"/>
   </joint>

   <link name="chassis">
     <visual>
       <origin xyz="0.15 0 0.075"/>
       <geometry>
          <box size ="0.3 0.3 0.15"/>
       </geometry>
       <material name="white"/>
          
      </visual>
       <collision>
       <origin xyz="0.15 0 0.075"/>
       <geometry>
          <box size ="0.3 0.3 0.15"/>
       </geometry>
          
      </collision>
      <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
         <origin xyz="0.15 0 0.075" rpy="0 0 0"/>
      </xacro:inertial_box>
   </link>
   
   <gazebo reference ="chassis">
    <material>Gazebo/Orange </material>
   </gazebo>

   <!--LEFT WHEEL LINK-->
   <joint name="wheel_left_joint" type="continuous">
      <parent link="base_link"/>
      <child link="wheel_left"/>
      <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
   </joint>

   <link name="wheel_left">
        <visual>
          <geometry>
            <cylinder length="0.05" radius="0.05"/>
          </geometry>
         <material name="black"/>
          </visual>
         <collision>
          <geometry>
            <cylinder length="0.05" radius="0.05"/>
          </geometry>
          </collision>
          <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
             <origin xyz="0 0 0" rpy="0 0 0"/>
          </xacro:inertial_cylinder>
   </link>       

   <gazebo reference ="wheel_left">
    <material>Gazebo/Black </material>

   </gazebo>
<!--RIGHT WHEEL LINK-->
   <joint name="wheel_right_joint" type="continuous">
      <parent link="base_link"/>
      <child link="wheel_right"/>
      <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 -1"/>
   </joint>

   <link name="wheel_right">
        <visual>
          <geometry>
            <cylinder length="0.05" radius="0.05"/>
          </geometry>
         <material name="black"/>
          </visual>
          <collision>
          <geometry>
            <cylinder length="0.05" radius="0.05"/>
          </geometry>
          </collision>
          <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
             <origin xyz="0 0 0" rpy="0 0 0"/>
          </xacro:inertial_cylinder>
          

   </link>   
   <gazebo reference ="wheel_right">
    <material>Gazebo/Black </material>
   </gazebo>

<!--CASTER WHEEL LINK-->
    <joint name="caster_wheel_joint" type="fixed">
      <parent link="chassis"/>
      <child link="caster_wheel"/>
      <origin xyz="0.25 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
               <sphere radius="0.05"/>
            </geometry>
            <material name="black"/>
         </visual>

          <collision>
            <geometry>
               <sphere radius="0.05"/>
            </geometry>
         </collision>
         <xacro:inertial_sphere mass="0.1"  radius="0.05">
             <origin xyz="0 0 0" rpy="0 0 0"/>
          </xacro:inertial_sphere>
    </link>     

   <gazebo reference ="caster_wheel">
     <material>Gazebo/Black </material>
     <mu1 value="0.001"/>
     <mu2 value="0.001"/>
   </gazebo>
</robot>